[package]
name = "rjq"
version = "0.1.0"
edition = "2018"
description = "simple jq command by Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
serde_json = "1.0"
clap = { version = "3.0.14", features = ["derive"] }
